// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxwmyjvzwcimlievpvjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4d215anZ6d2NpbWxpZXZwdmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNDQ5MjYsImV4cCI6MjA3OTkyMDkyNn0.Jc_0trjx87eT9qXlaOfxzgG7UUwNrIr14zvuoKeB24Y";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});